### ISSUE TITLE
exclude ` grid__cell-NN` styles from `grid__cell-NN_size-N`

### ISSUE THREAD

**Issue by iamstarkov** [iamstarkov/bem-bootstrap#6]
At now you can use only `grid__cell-NN_size-N` class and it works, but it is a mess and nightmare in css, so it `grid__cell-NN` and it's modifiers should be separated.

For example [this shitty selector](https://github.com/matmuchrapna/bem-bootstrap/blob/master/levels/core/grid/grid.css#L56-L61) (48 selectors (!) in one rule ):

``` css
.grid__cell-xs_size_1, .grid__cell-sm_size_1, .grid__cell-md_size_1, .grid__cell-lg_size_1, .grid__cell-xs_size_2, .grid__cell-sm_size_2, .grid__cell-md_size_2, .grid__cell-lg_size_2, .grid__cell-xs_size_3, .grid__cell-sm_size_3, .grid__cell-md_size_3, .grid__cell-lg_size_3, .grid__cell-xs_size_4, .grid__cell-sm_size_4, .grid__cell-md_size_4, .grid__cell-lg_size_4, .grid__cell-xs_size_5, .grid__cell-sm_size_5, .grid__cell-md_size_5, .grid__cell-lg_size_5, .grid__cell-xs_size_6, .grid__cell-sm_size_6, .grid__cell-md_size_6, .grid__cell-lg_size_6, .grid__cell-xs_size_7, .grid__cell-sm_size_7, .grid__cell-md_size_7, .grid__cell-lg_size_7, .grid__cell-xs_size_8, .grid__cell-sm_size_8, .grid__cell-md_size_8, .grid__cell-lg_size_8, .grid__cell-xs_size_9, .grid__cell-sm_size_9, .grid__cell-md_size_9, .grid__cell-lg_size_9, .grid__cell-xs_size_10, .grid__cell-sm_size_10, .grid__cell-md_size_10, .grid__cell-lg_size_10, .grid__cell-xs_size_11, .grid__cell-sm_size_11, .grid__cell-md_size_11, .grid__cell-lg_size_11, .grid__cell-xs_size_12, .grid__cell-sm_size_12, .grid__cell-md_size_12, .grid__cell-lg_size_12 {
    position: relative;
    min-height: 1px;
    padding-left: 15px;
    padding-right: 15px;
}
```

should be removed with replaced with this nice one:

``` css
.grid__cell-xs,
.grid__cell-md,
.grid__cell-lg
{
    position: relative;
    min-height: 1px;
    padding-left: 15px;
    padding-right: 15px;
}
```
